env:
  browser: true
  es2021: true
  mocha: true
extends: 'eslint:recommended'
parser: '@babel/eslint-parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  indent:
    - error
    - tab
  quotes:
    - error
    - single
  semi:
    - error
    - always
  curly:
    - error
  no-self-assign:
    - error
  no-unused-vars:
    - error
  no-eval:
    - error
  no-lonely-if:
    - error
  no-unneeded-ternary:
    - error
  no-useless-return:
    - error
  require-await:
    - error
  comma-style:
    - error
    - last
  comma-spacing:
    - error
    - before: false 
      after: true
  no-trailing-spaces:
    - error
  template-tag-spacing:
    - error
    - always
  keyword-spacing:
    - error
    - before: true
      after: true
globals:
  'Apice': true
  'ActiveXObject': true