# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/node:16.15.1
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test
      - run:
          name: Publish
          command: npm publish